### ISSUE TITLE
The displayed result is all black

### ISSUE THREAD

**Issue by HGD-ai** [itsroar/yolo_and_gst#1]
Hello, I have a question here that I would like to ask you for advice

My system version is as follows:

Ubuntu 20.04.6 LTS (GNU/Linux 5.10.110 aarch64)

Gst launch 1.0 version 1.16.2

GStreamer 1.16.2

I followed the readme instructions completely, and when I completed the operation, the displayed interface was completely black. May I ask why this is? Thank you very much for your reply！

**Comment by cmykcmyk1** [comment]
Hello, I will try to help you.
Could you please clarify:
1) Have you tried using a ready-made program?
2) Have you tried just opening the video through GStreamer?
For example, run: gst-launch-1.0 filesrc location="video.mp4" ! decodebin ! queue ! videoconvert ! xvimagesink
Is the video playing?)

No? Try with ximagesink (not xvimagesink).

If yes, then could you try to open main.cpp and edit 174 line. replace autovideosink -> xvimagesink (or ximagesink).

**Comment by HGD-ai** [comment]
Thank you very much for your reply. I followed your instructions and the results are as follows:

1、run: gst-launch-1.0 filesrc location="/my_ptah/test.mp4" ! decodebin ! queue ! videoconvert ! xvimagesink
Unable to play video and encountered the following error：
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstXvImageSink:xvimagesink0: Could not initialise Xv output

2、run: gst-launch-1.0 filesrc location="/my_ptah/test.mp4" ! decodebin ! queue ! videoconvert ! ximagesink
The displayed screen is still completely black, and the logs are as follows:
WARNING: from element /GstPipeline:pipeline0/GstVideoConvert:videoconvert0: Internal GStreamer error: code not implemented.  Please file a bug at http://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer.
Additional debug info:
gstvideofilter.c(292): gst_video_filter_transform (): /GstPipeline:pipeline0/GstVideoConvert:videoconvert0:
invalid video buffer received

Thank you again for your reply. Can you tell me what my problem is and how to solve it！

**Comment by cmykcmyk1** [comment]
Hm, maybe gst can't find required codec?
Now I thought, I should have advised you to start with an even simpler example:
gst-launch-1.0 videotestsrc ! decodebin ! queue ! videoconvert ! xvimagesink (or ximagesink)

Have you tried opening another video? Maybe it possible with my mp4?

**Comment by cmykcmyk1** [comment]
I just tried to open the mp4-file myself with --gst-debug-level=4.
It will output a long log, but if you try, you can find something interesting.
decodebin is generic element that defines video format and create specific video decoder.
And in my case decodebin created: qtdemux -> h264parse -> avdec_h264.
avdec_h264 is element from libav package (in my instruction sudo apt install gstreamer1.0-libav),
h264parse is from bad package (I didn't say install this package, and this is my fault).

I think you have not h264parse. Run:
gst-inspect-1.0 h264parse.
If you don't know, use autocompletion. Typed: "gst-inspect-1.0 h2", and press Tab. Sometimes need double press Tab.

So check `gst-inspect-1.0 h264parse` and `gst-inspect-1.0 avdec_h264`
For fast solve problem you can run:
`sudo apt install gstreamer1.0-plugins-bad`

When I wrote the instructions, I didn’t think that users would need to download a bad package.
I don't quite understand, but it seems that the developers themselves advise against using it.

**Comment by HGD-ai** [comment]
Thank you for your suggestion. I tried changing to another video and the result was the same. At the same time, I confirm that I have installed the H264 decoder. I also run sudo aptinstall gstreamer1.0 plugins bad. All the above methods have not solved my problem.

**Comment by HGD-ai** [comment]
I use the following commands to play different videos, some of which are displayed in black, while others are displayed in green.

Gst launch 1.0 playbin uri= file:///path/to/your/local/video/file

Is there a problem with my hardware device or software version?

**Comment by cmykcmyk1** [comment]
1) How about videotestsrc?
2) Is your Ubuntu running on a virtual machine or is it native?

**Comment by HGD-ai** [comment]
gst-launch-1.0 videotestsrc ! autovideosink
Executing the above command will display colored images normally. My ubuntu is a native version of 20.04

At the same time, I would like to ask how to turn off the display function. I suspect that there may be a problem with the display on my end

**Comment by cmykcmyk1** [comment]
If I understood the question correctly, you want to play the video but not display it.
gst-launch-1.0 filesrc ! decodebin ! queue ! videoconvert ! fakesink
gst-launch-1.0 filesrc ! decodebin ! queue ! videoconvert ! fakesink sync=true

is it ok?

**Comment by cmykcmyk1** [comment]
Maybe you need video driver?

**Comment by cmykcmyk1** [comment]
Can you run and say log:
1) xvinfo
2) glxinfo | grep OpenGL

**Comment by cmykcmyk1** [comment]
You OK?)

**Comment by HGD-ai** [comment]
I am very sorry for not replying to your message in a timely manner。The problem has not been solved yet. What I mean is that I want to turn off the display function in your code and only want to obtain the inference results of the model. I suspect that the inference results of the model are normal, but there is a problem with the display。

**Comment by HGD-ai** [comment]
Thank you very much for your help. I have resolved the previous issue by reinstalling gstreamer. Now I have a new problem where the displayed screen is always the same frame and has not been updated. May I ask if you have encountered this problem again?

**Comment by cmykcmyk1** [comment]
Hm, looks like the pipeline's clock is not starting.
Show me your pipeline.

**Comment by cmykcmyk1** [comment]
Also your mp4 if you can

**Comment by HGD-ai** [comment]
Here is my pipeline connection method, which should be the same as the source code you provided. I have not made any changes. At the same time, I am sure that my video file is fine and can be played normally.

  GstElement *pipeline = gst_pipeline_new("videoshow");

    GstElement *filesrc = gst_element_factory_make("filesrc", "videofile");
    g_object_set(filesrc, "location", filepath, NULL);

    GstElement *demux = gst_element_factory_make("qtdemux", "demux");
    g_signal_connect(demux, "pad-added", G_CALLBACK(on_demux_pad_added), pipeline);

    GstElement *queue_video = gst_element_factory_make("queue", "queue_video");
    GstElement *decodebin_video = gst_element_factory_make("decodebin", "decodebin_video");
    // link decodebin with other elements after some time, when decodebin read file metadata
    g_signal_connect(decodebin_video, "pad-added", G_CALLBACK(on_videodecoder_ready), pipeline);

    GstElement *videorate = gst_element_factory_make("videorate", "videorate");
    g_object_set(videorate, "max-rate", fps, NULL);

    GstElement *videoconvert1 = gst_element_factory_make("videoconvert", "videoconvert1");
    // setting our callback for edit video
    GstPad *vc_output = gst_element_get_static_pad(videoconvert1, "src");
    gst_pad_add_probe(vc_output, GST_PAD_PROBE_TYPE_BUFFER, on_pad_probe, NULL, NULL);
    gst_object_unref(vc_output);

    GstElement *capsfilter = gst_element_factory_make("capsfilter", "rgb_filter");
    GstCaps *caps = gst_caps_new_simple("video/x-raw", "format", G_TYPE_STRING, "RGB", NULL);
    g_object_set(G_OBJECT(capsfilter), "caps", caps, NULL);
    gst_caps_unref(caps);

    GstElement *videoconvert2 = gst_element_factory_make("videoconvert", "videoconvert2");
    GstElement *videosink = gst_element_factory_make("autovideosink", "videosink");
    //GstElement *videosink = gst_element_factory_make("appsink", "videosink");

    GstElement *queue_audio = gst_element_factory_make("queue", "queue_audio");
    GstElement *decodebin_audio = gst_element_factory_make("decodebin", "decodebin_audio");
    g_signal_connect(decodebin_audio, "pad-added", G_CALLBACK(on_audiodecoder_ready), pipeline);

    GstElement *audioconvert = gst_element_factory_make("audioconvert", "audioconvert");
    GstElement *audiosink = gst_element_factory_make("autoaudiosink", "audiosink");

    if (!pipeline || !filesrc || !demux || !queue_video || !decodebin_video ||
        !videorate || !videoconvert1 || !capsfilter || !videoconvert2 || !videosink ||
        !queue_audio || !decodebin_audio || !audioconvert || !audiosink)
    {
        g_printerr ("Not all elements could be created.\n");
        return -1;
    }

    gst_bin_add_many(GST_BIN(pipeline), filesrc, demux,
                     queue_video, decodebin_video, videorate, videoconvert1, capsfilter, videoconvert2, videosink,
                     queue_audio, decodebin_audio, audioconvert, audiosink, NULL);

    if (gst_element_link(filesrc, demux) != TRUE ||
        gst_element_link(queue_video, decodebin_video) != TRUE ||
        gst_element_link_many(videorate, videoconvert1, capsfilter, videoconvert2, videosink, NULL) != TRUE ||
        gst_element_link(queue_audio, decodebin_audio) != TRUE ||
        gst_element_link(audioconvert, audiosink) != TRUE)
    {
        g_printerr("Elements could not be linked.\n");
        gst_object_unref(pipeline);
        return -1;
    }

**Comment by cmykcmyk1** [comment]
I want to understand can you playback your videofile from gst-launch-1.0.
When I did this project, I worked with h264-video.
Maybe your video has another videocodec, and you need to some change in your pipeline.
Run in terminal:
`gst-launch-1.0 filesrc location="video.mp4" ! qtdemux name=demux ! queue ! decodebin ! videoconvert ! autovideosink demux. ! queue ! decodebin ! audioconvert ! autoaudiosink`

**Comment by HGD-ai** [comment]
Thank you very much for your continuous reply. At present, I have only retained elements related to the video and used OpenCV to read the image, which has solved the previous problem. The image can be displayed normally, but now I have discovered that there may be a memory leak and the video being played may be lagging

**Comment by cmykcmyk1** [comment]
Is there anything else required from me?)

**Comment by HGD-ai** [comment]
I have no further questions. Thank you very much for your help.
