### ISSUE TITLE
How to replace filesrc with uridecodebin

### ISSUE THREAD

**Issue by HGD-ai** [itsroar/yolo_and_gst#2]
Now I want the program to freely read RTSP streams and local video files. So I want to replace filesrc with uridecodebin. But it has not been successful. I wonder if you have time to guide me. Thank you very much, I have caused you trouble again. Here is my main function program, please take a look. My main function program always display Failed to link source and demux. In addition,when I don't use the demux element, I simply combine the source and queue_video connection was also unsuccessful with the link.

int main(int argc, char *argv[]) {
 
    int fps=25;
    gst_init(&argc, &argv);
    GstElement *pipeline = gst_pipeline_new("videoshow");
 
    //source = gst_element_factory_make("uridecodebin", "source");
//    GstElement *source = gst_element_factory_make("filesrc", "videofile");
//    g_object_set(source, "location", "/home/ema/Deploy/GInfer/data/test3.mp4", NULL);

    GstElement *source = gst_element_factory_make("uridecodebin", "source");
    g_object_set(source, "uri", "file:///home/ema/Deploy/GInfer/data/test.mp4", NULL);

    GstElement *demux = gst_element_factory_make("qtdemux", "demux");
    g_signal_connect(demux, "pad-added", G_CALLBACK(on_demux_pad_added), pipeline);

    GstElement *queue_video = gst_element_factory_make("queue", "queue_video");
    GstElement *decodebin_video = gst_element_factory_make("decodebin", "decodebin_video");
    // link decodebin with other elements after some time, when decodebin read file metadata
    g_signal_connect(decodebin_video, "pad-added", G_CALLBACK(on_videodecoder_ready), pipeline);

    GstElement *videorate = gst_element_factory_make("videorate", "videorate");
    g_object_set(videorate, "max-rate", fps, NULL);

    GstElement *videoconvert1 = gst_element_factory_make("videoconvert", "videoconvert1");
    // setting our callback for edit video
    GstPad *vc_output = gst_element_get_static_pad(videoconvert1, "src");
    gst_pad_add_probe(vc_output, GST_PAD_PROBE_TYPE_BUFFER, on_pad_probe, NULL, NULL);
    gst_object_unref(vc_output);

    GstElement *capsfilter = gst_element_factory_make("capsfilter", "rgb_filter");
    GstCaps *caps = gst_caps_new_simple("video/x-raw", "format", G_TYPE_STRING, "BGR", NULL);
    g_object_set(G_OBJECT(capsfilter), "caps", caps, NULL);
    gst_caps_unref(caps);

    GstElement *videoconvert2 = gst_element_factory_make("videoconvert", "videoconvert2");
    //GstElement *videosink = gst_element_factory_make("autovideosink", "videosink");
    GstElement *videosink = gst_element_factory_make("fakesink", "videosink");
    g_object_set(videosink, "sync", FALSE, NULL);

    //GstElement *videosink = gst_element_factory_make("appsink", "videosink");

   if (!pipeline || !source || !demux || !queue_video || !decodebin_video ||
    !videorate || !videoconvert1 || !capsfilter || !videoconvert2 || !videosink)
    {
        g_printerr ("Not all elements could be created.\n");
        return -1;
    }
   gst_bin_add_many(GST_BIN(pipeline), source,demux,
                     queue_video, decodebin_video, videorate, videoconvert1, capsfilter, videoconvert2, videosink,
                    NULL);

   if (!gst_element_link(source, demux)) {
    g_printerr("Failed to link source and demux.\n");
    gst_object_unref(pipeline);
    return -1;
}

   if (!gst_element_link(demux, queue_video)) {
    g_printerr("Failed to link source and queue_video.\n");
    gst_object_unref(pipeline);
    return -1;
}

// link queue_video和decodebin_video
if (!gst_element_link(queue_video, decodebin_video)) {
    g_printerr("Failed to link queue_video and decodebin_video.\n");
    gst_object_unref(pipeline);
    return -1;
}

// link decodebin_video和videorate
if (!gst_element_link(decodebin_video, videorate)){
    g_printerr("Failed to link decodebin_video and videorate.\n");
    gst_object_unref(pipeline);
    return -1;
}

// link videorate和videoconvert1
if (!gst_element_link(videorate, videoconvert1)){
    g_printerr("Failed to link videorate and videoconvert1.\n");
    gst_object_unref(pipeline);
    return -1;
}

// link videoconvert1和capsfilter
if (!gst_element_link(videoconvert1, capsfilter)){
    g_printerr("Failed to link videoconvert1 and capsfilter.\n");
    gst_object_unref(pipeline);
    return -1;
}

// link capsfilter和videoconvert2
if (!gst_element_link(capsfilter, videoconvert2)){
    g_printerr("Failed to link capsfilter and videoconvert2.\n");
    gst_object_unref(pipeline);
    return -1;
}

// link videoconvert2和videosink
if (!gst_element_link(videoconvert2, videosink)){
    g_printerr("Failed to link videoconvert2 and videosink.\n");
    gst_object_unref(pipeline);
    return -1;
}

   
    GstStateChangeReturn ret = gst_element_set_state(pipeline, GST_STATE_PLAYING);
    if (ret == GST_STATE_CHANGE_FAILURE)
    {
        g_printerr("Unable to set the pipeline to the playing state.\n");
        gst_object_unref(pipeline);
        return -1;
    }

    GstBus *bus = gst_element_get_bus(pipeline);
    GstMessage *msg = gst_bus_timed_pop_filtered(bus, GST_CLOCK_TIME_NONE, GstMessageType(GST_MESSAGE_ERROR | GST_MESSAGE_EOS));

    if (msg != NULL) {
        GError *err;
        gchar *debug_info;

        switch (GST_MESSAGE_TYPE(msg)) {
        case GST_MESSAGE_ERROR:
            gst_message_parse_error(msg, &err, &debug_info);
            g_printerr("Error received from element %s: %s\n",
                        GST_OBJECT_NAME (msg->src), err->message);
            g_printerr("Debugging information: %s\n",
                        debug_info ? debug_info : "none");
            g_clear_error(&err);
            g_free(debug_info);
            break;
        case GST_MESSAGE_EOS:
            g_print("End-Of-Stream reached.\n");
            break;
        default:
            /* We should not reach here because we only asked for ERRORs and EOS */
            g_printerr("Unexpected message received.\n");
            break;
        }
        gst_message_unref(msg);
    }

    gst_object_unref(bus);
    gst_element_set_state(pipeline, GST_STATE_NULL);
    gst_object_unref(pipeline);
    return 0;
}

**Comment by cmykcmyk1** [comment]
I only succeeded with absolute path:
```
gst-launch-1.0 uridecodebin uri=file:///media/sf_Z/vidosychi/Hi\ Jack.mp4 name=demux ! queue ! videoconvert ! xvimagesink demux. ! queue ! audioconvert ! audioresample ! autoaudiosink
gst-launch-1.0 uridecodebin uri="file:///media/sf_Z/vidosychi/Hi Jack.mp4" name=demux ! queue ! videoconvert ! xvimagesink demux. ! queue ! audioconvert ! audioresample ! autoaudiosink
```

Do you know about gst_parse_launch?
Now I prefer to use this instead of manually building a pipeline.

**Comment by HGD-ai** [comment]
Thank you for your guidance. I feel that I need to further study the relevant knowledge of gsteam. I would like to express my gratitude once again for the high-quality project code you provided

**Comment by cmykcmyk1** [comment]
Thank you too. If you want, write to me in Telegram.
